# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-13 15:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': '\u7528\u6237\u53cd\u9988', 'verbose_name_plural': '\u7528\u6237\u53cd\u9988'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='emailfeedback',
            field=models.EmailField(default=datetime.datetime(2017, 12, 13, 15, 10, 44, 843034), max_length=50, verbose_name='\u90ae\u7bb1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='xingming',
            field=models.CharField(default=datetime.datetime(2017, 12, 13, 15, 11, 4, 680187), max_length=10, verbose_name='\u59d3\u540d'),
            preserve_default=False,
        ),
    ]
